### ISSUE TITLE
UDP loopback IP transport problems

### ISSUE THREAD

**Issue by dogfight360** [yinghuocho/gotun2socks#6]
Listen to loopback IP:127.0.0.1
TCP and UDP work properly

but Listen to loopback IP:127.0.0.2 or 2-255
TCP is working properly, UDP can not be transport

send
Application.UDP------>gotun2socks------>server------>target
recv
Application.UDP--x---<gotun2socks------<server------<target

The packet passes through the server and returns
But there is no return from the gotun2socks to the Application

**Comment by yinghuocho** [comment]
@wu360463231 I just fixed a bug in gotun2socks's UDP processing, which may cause the problem you described. Please update the code and test again and let me know the result. Thanks.

**Comment by dogfight360** [comment]
UDP Still does not work
Socks5 listen to loopback IP: 127.0.0.2 or 2-255

**Comment by yinghuocho** [comment]
I tried to listen socks5 proxy on 127.0.0.2. UDP tunnelling worked fine.

**Comment by dogfight360** [comment]
May be shadowsocksR c# client error?
but openvpn UDP mode working
